

# This file was *autogenerated* from the file solver.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_300 = Integer(300); _sage_const_10 = Integer(10); _sage_const_103 = Integer(103); _sage_const_2 = Integer(2)
import os
os.environ['PWNLIB_NOTERM'] = 'True' # sage & pwntools

from pwn import *
import re

io = remote('crt.cry.wanictf.org','50000')
P = Primes()

p = _sage_const_1 
rets, primes = [], []
while True:
    p = P.next(p)
    if p > _sage_const_300 :
        break
    io.recvuntil('Mod > ')
    io.sendline(str(p))
    ret = int(re.sub(r'\D','',io.recvline().decode('utf-8')))
    rets.append(ret)
    primes.append(p)

flag = CRT_list(rets,primes)

assert flag <= _sage_const_10  ** _sage_const_103 

print(bytes.fromhex(hex(flag)[_sage_const_2 :]))

