

# This file was *autogenerated* from the file solver.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_28572 = Integer(28572); _sage_const_1 = Integer(1)
from pwn import *
import re
from Crypto.Util.number import *

e, n, c = _sage_const_3 , [], []

for _ in range(_sage_const_3 ):
    io = remote('193.57.159.27', _sage_const_28572 )
    io.recvline() # e
    n.append(int(re.search(r'n: (\d+)' , str(io.recvline())).group(_sage_const_1 )))

    io.recvuntil('opt: ')
    io.sendline('2')
    c.append(int(re.search(r'c: (\d+)' , str(io.recvline())).group(_sage_const_1 )))
    io.close()

x = CRT_list(c,n)

print(long_to_bytes(x**(_sage_const_1 /e)))

